"""add custom_id to Worker

Revision ID: 72320e91abcf
Revises: ac6338858180
Create Date: 2025-07-07 11:42:39.854674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72320e91abcf'
down_revision: Union[str, Sequence[str], None] = 'ac6338858180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_documents_id'), table_name='company_documents')
    op.drop_table('company_documents')
    op.add_column('workers', sa.Column('custom_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_workers_custom_id'), 'workers', ['custom_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_custom_id'), table_name='workers')
    op.drop_column('workers', 'custom_id')
    op.create_table('company_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('filetype', sa.VARCHAR(), nullable=False),
    sa.Column('filepath', sa.VARCHAR(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_documents_id'), 'company_documents', ['id'], unique=False)
    # ### end Alembic commands ###
